Repository precice/fenicsx-adapter, pull requests merged in 2022-12, with the labels that each got.

#14 Fixing the partitioned-heat-equation tutorial
  fenicsxprecice/expression_core.py
  tutorials/partitioned-heat-conduction/fenicsx/errorcomputation.py
  tutorials/partitioned-heat-conduction/fenicsx/heat.py
  tutorials/partitioned-heat-conduction/fenicsx/problem_setup.py
Labels: bug

#18 Fix broken links
  .github/workflows/check-links.yml
  .github/workflows/check-markdown.yml
  .markdown-link-check-config.json
  README.md
  docs/ReleaseGuide.md
  tutorials/partitioned-heat-conduction/README.md
Labels: documentation

#20 Move to target version v0.5.2.
  .github/workflows/build-and-test.yml
  README.md
Labels: enhancement
